################################
env_suite: robomimic
env_name: can

obs_dim: 23
cond_steps: 1

action_dim: 7
horizon_steps: 4
act_steps: 4
################################
defaults:
  - _self_
hydra:
  run:
    dir: ${logdir}
_target_: agent.finetune.robofft_f.train_fpo_flow_agent.TrainFPOFlowAgent
name: ${env_name}_robofft_reflow_mlp_ta${horizon_steps}_td${denoising_steps}_tdf${ft_denoising_steps}_seed${seed}
logdir: ${oc.env:ROBOFFT_F_LOG_DIR}/robomimic/finetune/${env_name}_robofft_reflow_mlp_ta${horizon_steps}_td${denoising_steps}_tdf${ft_denoising_steps}/${now:%Y-%m-%d}_${now:%H-%M-%S}_${seed}
base_policy_path: log/robomimic/pretrain/can/can_pre_reflow_mlp_ta4_td100/2026-03-25_21-00-28_42/checkpoint/state_3000.pt
robomimic_env_cfg_path: cfg/robomimic/env_meta/${env_name}.json
normalization_path: ${oc.env:ROBOFFT_F_DATA_DIR}/robomimic/${env_name}/normalization.npz

seed: 42
device: cuda:0
sim_device: cuda:0
#########################
denoising_steps: 10
ft_denoising_steps: 10
min_std: 0.25
max_std: 0.25
#########################

env:
  n_envs: 50
  name: ${env_name}
  best_reward_threshold_for_success: 1
  max_episode_steps: 300
  save_video: False
  wrappers:
    #robomimic_lowdim:
    robomimic_lowdim:
      normalization_path: ${normalization_path}
      low_dim_keys: ['robot0_eef_pos',
                    'robot0_eef_quat',
                    'robot0_gripper_qpos',
                    'object'] # same order of preprocessed observations
    multi_step:
      n_obs_steps: ${cond_steps}
      n_action_steps: ${act_steps}
      max_episode_steps: ${env.max_episode_steps}
      reset_within_step: True


wandb:
  entity: ${oc.env:ROBOFFT_F_WANDB_ENTITY}
  project: robomimic-${env_name}-finetune
  run: ${now:%Y-%m-%d}_${now:%H-%M-%S}_${name}
  offline_mode: false
train:
  n_train_itr: 151
  n_critic_warmup_itr: 2
  n_steps: 300
  gamma: 0.999
  actor_lr: 2e-6
  actor_weight_decay: 0
  actor_lr_scheduler:
    type: cosine
    first_cycle_steps: ${train.n_train_itr}
    warmup_steps: 10
    min_lr: 1e-6
  critic_lr: 1e-3
  critic_weight_decay: 0
  critic_lr_scheduler:
    type: cosine
    first_cycle_steps: ${train.n_train_itr}
    warmup_steps: 10
    min_lr: 1e-3
  save_model_freq: 100
  val_freq: 10
  render:
    freq: 1
    num: 0
  # PPO/FPO specific
  reward_scale_running: true
  reward_scale_const: 1.0
  gae_lambda: 0.95
  batch_size: 10000
  logprob_batch_size: 500
  update_epochs: 10
  vf_coef: 0.5
  target_kl: 1e-2
  lr_schedule: fixed
  repeat_samples: true
  verbose: false
  clip_intermediate_actions: true
  account_for_initial_stochasticity: true
  n_samples_per_action: 1
model:
  _target_: model.flow.ft_fpo.fpoflow.FPOFlow
  device: ${device}
  actor_policy_path: ${base_policy_path}
  policy:
    _target_: model.flow.mlp_flow.FlowMLP
    horizon_steps: ${horizon_steps}
    action_dim: ${action_dim}
    cond_dim: ${eval:'${obs_dim} * ${cond_steps}'}
    time_dim: 16
    mlp_dims: [512, 512, 512]
    use_layernorm: false
    residual_style: true
  critic:
    _target_: model.common.critic.CriticObs
    mlp_dims: [256, 256, 256]
    activation_type: Mish
    residual_style: true
    cond_dim: ${eval:'${obs_dim} * ${cond_steps}'}
  act_dim: ${action_dim}
  horizon_steps: ${horizon_steps}
  act_min: -1
  act_max: 1
  obs_dim: ${obs_dim}
  cond_steps: ${cond_steps}
  noise_scheduler_type: learn
  inference_steps: ${denoising_steps}
  ft_denoising_steps: ${ft_denoising_steps}
  randn_clip_value: 3
  min_sampling_denoising_std: ${min_std}
  min_logprob_denoising_std: ${min_std}
  max_logprob_denoising_std: ${max_std}
  logprob_min: -1.0
  logprob_max: 1.0
  logratio_alpha: 8.0
  ################################################
  clip_ploss_coef: 0.02
  clip_ploss_coef_base: 0.001             # changed from 0.01 to 0.001
  clip_ploss_coef_rate: 3                 # same as DPPO
  clip_vloss_coef: null
  denoised_clip_value: 1.0
  ################################################
  time_dim_explore: 0
  learn_explore_time_embedding: false     # needs change ?
  use_time_independent_noise: true        # needs change ? 
  noise_hidden_dims: [128,128]            
  logprob_debug_sample: false
  logprob_debug_recalculate: false
  explore_net_activation_type: Tanh
  # FPO specific
  sample_t_type: linspace
  n_samples_per_action: ${train.n_samples_per_action}
  matching_style: u
  zero_start_eval: false
  zero_start_train: false